server:
  port: 11001

spring:
  application:
    name: BOOKKEEPING-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/b1uebank/BookkeepingServiceRegistry
          clone-on-start: true